### ISSUE TITLE
Getting Started for erlang/elixir doesn't work as described: no span output for request without setting up span explicitly 

### ISSUE THREAD

**Issue by tomwang57** [open-telemetry/opentelemetry.io#5289] opened 2024-10-02 06:15 UTC
I followed the guide in https://opentelemetry.io/docs/languages/erlang/getting-started/ to setup a phoenix project:

https://github.com/tomwang57/opentelemetry_test_elixir

When i didn't explicitly setup a span with `Tracer.with_span`, there was no span output. It was against what the guild said that there should be span output for every request by default.

**Comment by svrnm** [comment] 2024-10-02 07:52
@tomwang57 thanks for reporting

@open-telemetry/erlang-approvers can you take a look?

**Comment by ferd** [comment] 2024-10-02 13:18
Yeah I had a similar issue just a couple days ago when revising how one of my apps sets up its tracing, where `with_span` isn't an acceptable macro because of how my workflow is set up.

Whenever I used `start_span` and `end_span` together, I ended up not getting output. Looking into the ETS tables of my node however, I could see that the spans were started, just never ended. 

As it turns out, I think the default macro'd `end_span` implementation requires context to be set up more thoroughly otherwise it doesn't know what to end. 

I ended up having to [set up my own wrappers](https://github.com/ferd/ReVault/blob/fcd432f4367e7ee2fdd716035820d7258522fe48/apps/revault/src/revault_otel.erl#L10-L36) that specifically replicate what `with_span` does:

1. start the span (and track the span context it returns)
2. call the tracer to set the span from 1. as the active span
3. attach the context to get a token

Then when ending the span:

4. reusing the span context from 1. and passing it to `end_span`'s non-macro version
5. setting the current context again
6. detaching from the token

I believe step 6 (but maybe 5 as well) are required for all future child spans _not_ to be considered children of the span that was just closed.

I know I've discussed these issues privately with @tsloughter recently, I don't know if he has better ideas of what to do about it rather than just keep that complexity in place or always advocate for `with_span`

**Comment by bryannaegele** [comment] 2024-10-02 15:52
Python created a convenience function of `start_as_current_span` which we could look at adding. I'd rather we use any existing conventions from other langs where there's not something currently in the spec. I haven't done a survey of all languages, just happen to currently be working in some python code.

**Comment by tsloughter** [comment] 2024-10-02 16:01
And actually, I think @tomwang57 is only referring to the Phoenix instrumentation not working correctly, right?

**Comment by tomwang57** [comment] 2024-10-02 23:52
> And actually, I think @tomwang57 is only referring to the Phoenix instrumentation not working correctly, right?

Yes, I've no idea about what others said.

**Comment by bryannaegele** [comment] 2024-10-03 02:08
The example linked repo is using bandit, not cowboy, so that is expected behavior right now. Please set your project to use cowboy. 

If that's a fork of the current example, that is an error in there

**Comment by tomwang57** [comment] 2024-10-04 10:13
> The example linked repo is using bandit, not cowboy, so that is expected behavior right now. Please set your project to use cowboy.
> 
> If that's a fork of the current example, that is an error in there

So is there any counterpart option for `bandit` like `opentelemetry_bandit`?

**Comment by svrnm** [comment] 2024-10-08 09:29
@tomwang57 any reason why you closed this issue? This does not seem to be resolved?

**Comment by svrnm** [comment] 2024-10-08 09:35
Ah thanks for clarification! Is it worth to add a note to the page such that others will not face the same issue?

**Closed** 2024-11-26 09:43 UTC
Labels: sig:erlang
