### ISSUE TITLE
Code-block rendering issue in Safari

### ISSUE THREAD

**Issue by njacobs5074** [open-telemetry/opentelemetry.io#3538] opened 2023-11-14 11:35 UTC
Some of the code samples are not rendering in Safari Version 17.1 (19616.2.9.11.7) on macOS 14.1.1 (23B81)

The cut & paste button does work so I can view the code in a separate editor.

I have attached a screenshot for your reference

<img width="1537" alt="Screenshot 2023-11-14 at 13 29 37" src="https://github.com/open-telemetry/opentelemetry.io/assets/8927466/75d05ac8-0420-4af2-82cc-b629fad9f581">

**Comment by svrnm** [comment] 2023-11-14 11:37
Thanks for reporting @njacobs5074, I can reproduce this issue for https://opentelemetry.io/docs/instrumentation/java/manual/#create-spans

**Comment by chalin** [comment] 2023-11-14 11:51
Oh! I'm on it!

**Comment by chalin** [comment] 2023-11-14 11:54
Hmm. Firefox is happy (as is Chrome, of course :))

**Comment by chalin** [comment] 2023-11-14 12:01
Renders fine when served locally. It seems to be restricted to code blocks with line highlights like this:

~~~markdown
```java { hl_lines=["6-9","19-22"] }
package otel;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.Banner;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import io.opentelemetry.api.OpenTelemetry;
import io.opentelemetry.sdk.autoconfigure.AutoConfiguredOpenTelemetrySdk;

@SpringBootApplication
public class DiceApplication {
  public static void main(String[] args) {
    SpringApplication app = new SpringApplication(DiceApplication.class);
    app.setBannerMode(Banner.Mode.OFF);
    app.run(args);
  }

  @Bean
  public OpenTelemetry openTelemetry() {
    return AutoConfiguredOpenTelemetrySdk.initialize().getOpenTelemetrySdk();
  }
}
```
~~~

**Comment by chalin** [comment] 2023-11-14 12:35
No, it's not specific to code blocks using line highlighting.

Ah, I've seen this Safari bug before! Safari is creating elements of unreasonable height, e.g., for the first code block of the section https://opentelemetry.io/docs/instrumentation/java/manual/#create-spans:

> <img width="944" alt="image" src="https://github.com/open-telemetry/opentelemetry.io/assets/4140793/fdb7b9ae-5e5d-4ed5-8529-92c8bc10b637">

Note how the height of the code block is 17K px!

**Comment by chalin** [comment] 2023-11-14 12:45
Fixed in:

- #3539

Can you test it out? Here's the preview link: https://deploy-preview-3539--opentelemetry.netlify.app/docs/instrumentation/java/manual/#create-spans

**Closed** 2023-11-14 13:07 UTC
Labels: bug, design/style
