### ISSUE TITLE
Feat: Enable Dark Mode for Search Results Box

### ISSUE THREAD

**Issue by moiz2405** [open-telemetry/opentelemetry.io#5701] opened 2024-11-27 17:48 UTC
**Desired feature or idea**: 
White background of search results is looking odd in dark mode
Dark mode can be enabled for the search result's box for a more uniform look on the UI, it is a small feature but adds to the overall attention to detail. 

**Additional context**: 
As shown below dark mode hook can be used on the overall container while each searched item div can stay the same.

![Screenshot 2024-11-27 230815](https://github.com/user-attachments/assets/2e4eff76-b676-4918-ba9a-acbe5bcda5c0)

**Comment by svrnm** [comment] 2024-12-04 08:48
thanks for reporting @moiz2405 

this might be an upstream issue since we use [docsy](https://github.com/google/docsy/)'s feature to pull in google search engine.

@chalin FYI

**Comment by chalin** [comment] 2024-12-05 21:01
Right, this is a duplicate of:

- #4776

**Closed by chalin** 2024-12-05 21:01 UTC
