### ISSUE TITLE
Permission denied issue for file exporter

### ISSUE THREAD

**Issue by SantoshAvaji** [open-telemetry/opentelemetry.io#4297] opened 2024-04-15 18:28 UTC
This problem is more appropriate in the otel col contrib repo, However, I think you should read the `fileexporter's` readme.md carefully first: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/fileexporter

> The official [opentelemetry-collector-contrib container](https://hub.docker.com/r/otel/opentelemetry-collector-contrib/tags#!) does not have a writable filesystem by default since it's built on the scratch layer. As such, you will need to create a writable directory for the path, potentially by mounting writable volumes or creating a custom image.

myconfig.yaml
receivers:

    otlp:

      protocols:

        grpc:

          endpoint: [0.0.0.0:4317](http://0.0.0.0:4317/)

        http:

          endpoint: [0.0.0.0:4318](http://0.0.0.0:4318/)

processors:

    batch:

 

exporters:

    file:

      path: ./logs/test.txt

 

extensions:

  health_check:

  pprof:

  zpages:

 

service:

    extensions: [health_check, pprof, zpages]

    pipelines:

        traces:

            receivers: [otlp]

            processors: [batch]

            exporters: [file]

       metrics:

            receivers: [otlp]

            processors: [batch]

            exporters: [file]

                                logs:

          receivers: [otlp]

          processors: [batch]

          exporters: [file]

     Command Executed :sudo docker run -v ./myconfig.yaml:/etc/otelcol-contrib/config.yaml -v ./te./logs:/logs  otel/opentelemetry-collector-contrib:0.97.0

 

Error: cannot start pipelines: open ./logs/test.txt: permission denied

2024/04/15 17:23:54 collector server run finished with error: cannot start pipelines: open ./logs/test.txt: permission denied

**Comment by svrnm** [comment] 2024-04-16 07:18
Duplicate of https://github.com/open-telemetry/community/discussions/2055

**Closed by svrnm** 2024-04-16 07:18 UTC
