### ISSUE TITLE
Host community pages via repo submodule

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#1809] opened 2022-10-05 16:59 UTC
via https://github.com/open-telemetry/community/pull/1056:

> Discussed in the GC call. GC recommendation is to use the same publishing mechanism for Community repo that we already use for including Specification into the website pages.

> My personal suggestion: instead of using a submodule, use a web hook and pull the dependency repos at build time. This will eliminate the need for manual submodule hash updates and will keep the docs up-to-date with the Specs/Community automatically (one possible downside is if commits in those repos end up breaking the build of the website, e.g. by using invalid link).

**Comment by chalin** [comment] 2022-10-05 18:28
We're using submodules already, I'd rather continue using submodules (easier to reproduce builds IMHO).

**Comment by chalin** [comment] 2023-01-24 20:09
@svrnm - are you ok with a change in title for this issue, something like: **Host community pages via repo submodule**?

**Comment by svrnm** [comment] 2023-02-02 14:22
> @svrnm - are you ok with a change in title for this issue, something like: **Host community pages via repo submodule**?

Yes, let's change it to that.

**Comment by chalin** [comment] 2023-02-20 21:46
Closing, since the community repo is now a submodule. For the mission page work, see:

- #1289

**Closed by chalin** 2023-02-20 21:46 UTC
Labels: enhancement, infrastructure
