### ISSUE TITLE
Community and Specification content

### ISSUE THREAD

**Issue by tedsuo** [open-telemetry/opentelemetry.io#12] opened 2019-05-30 06:43 UTC
We will have a fair amount of content in the community and spec repos which we also want to be available directly on the website. This content needs to live in these other repos, due having a different approval process. How should it live in both places? We could copy the changes over to the website by hand, but that feels both brittle and tedious. 

Since the content in all three repos is written in markdown, the simplest solution might be to just embed these other repos as submodules, along with a build script that automatically updates them to the latest commit. @lucperkins, having done this song and dance a couple of times now, do you have a preferred approach?

**Comment by lucperkins** [comment] 2019-05-30 14:34
@tedsuo I think the same submodule-driven approach we took for the OpenTracing site is the way to go. Feel free to point me to content that you'd like to include and I can work up a system for doing so.

**Comment by SergeyKanzhelev** [comment] 2019-06-20 23:19
This repo now has a lot of content: https://github.com/open-telemetry/opentelemetry-specification/

@lucperkins do you have any feedback on the structure of the repository? Basically, top level README.md is a starting point for specs, terminology, etc. Can you make the repo into the website?

**Comment by lucperkins** [comment] 2019-06-24 01:33
@SergeyKanzhelev I'm going to do my best to bring that material into the website. If any changes are necessary, I can submit a PR to that repo. Shouldn't be too hard in general.

**Comment by lucperkins** [comment] 2019-07-02 20:16
@SergeyKanzhelev @tedsuo So, I'm doing some digging, and I don't think it's going to work in the spec's current form. The issue is that a lot of the spec documents contain image links and relative links to other documents, such as the README, that won't work when transported outside that context. I'm going to see what I can do but it's possible that we won't be able to display the spec under opentelemetry.io.

**Comment by lucperkins** [comment] 2019-07-02 21:23
@SergeyKanzhelev @tedsuo Actually, it turns out that this is an issue for OpenTracing as well: https://github.com/opentracing/opentracing.io/issues/349.

**Comment by tedsuo** [comment] 2019-07-03 18:37
Oof, yeah that is a tricky wicket. I wonder if there are ways we can change the spec and community repos to make embedding easier. Obviously this was not a requirement when we started.

Some questions:
* Would it be helpful to flatten the repo to a single folder? Right now some content is nested, but it is not really necessary.
* Can we write links / urls in a certain way to make them work in both cases? Would relative links work better if the repo was flat? AKA is it only the "../../" portion of links which are an issue?
* Is there an issue specific to hosting images, or is it just a general issue with linking?

I'd prefer us to clean things up so that these repos can just be dropped in as submodules. If we can't make that happen, is there a simple find/replace pattern we could run as a script to fix the links?

**Comment by lucperkins** [comment] 2019-07-11 20:43
@tedsuo There are basically two things that need to happen:

1. `../foo.md` links need to be converted to `../foo`
2. Page metadata of this form needs to be attached to each page:

    ```
    ---
    title: Some document
    ---
    ```

#2 is easily achieved by changing the docs directly in the spec folder and committing those changes. #1 necessarily requires some kind of swap-out logic.

**Comment by tedsuo** [comment] 2019-07-16 16:01
Blech. That's a bummer. On the one hand, I want these docs on the website. But I see how this can sprawl... rewriting anchor links and other nonsense... sadness.

I'm open to creative solutions here. But for now, I agreer we should just link to the repos.

**Comment by austinlparker** [comment] 2019-07-16 18:29
As the person that broke the spec on opentracing.io (😂) I'm going to put a vote in favor of linking to the repos. I'd suggest that we look into ways to logically separate the 'documentation' from the 'specification', or create a consistent approach to allow for per-language documentation to be hosted on the website. Seems to me that language docs are going to be more valuable from a discovery/search point of view anyway?

**Comment by lucperkins** [comment] 2019-07-16 18:56
@tedsuo One possible solution would be to restructure the specification docs in a way that makes those docs immediately consumable by the site generator (i.e. break the Markdown links and add page metadata). It could be made abundantly clear in the specification repo README that that repo is "write only," i.e. only of interest to people working on the spec, and that opentelemetry.io is the canonical presentation layer for the spec. If you're okay with that approach let me know and I can quickly make that happen.

**Comment by lucperkins** [comment] 2019-07-17 20:00
@austinlparker Logically separating the spec and the "docs" has definitely been the plan all along. The per-language docs will eventually live here in this repo and be part of an integrated experience. The spec will be the only exception to that and only for logistical reasons (**sigh**).

**Comment by austinlparker** [comment] 2019-07-17 20:53
The canonical presentation layer is a good idea, imo.

**Comment by lucperkins** [comment] 2019-07-19 17:59
@austinlparker Okay. If I can get a quorum of core maintainers on board I'm happy to make that happen.

**Comment by austinlparker** [comment] 2020-11-09 17:15
FYI this was briefly discussed and there was a general consensus in the last comms SIG, so I'm going to write up "where we're at" and close this issue.

Things that should be documented in the website:
- General OTel Concepts
- General use cases and practices (i.e., interpreting telemetry data or instrumenting across a queue)
- Stable "end user" documentation for released versions of OTel components (collector, sdk)

Things that can be documented in each SIG repo or elsewhere:
- In-progress documentation for unreleased versions of OTel
- Specific configuration information for plugins, components, etc.
- Technical API/SDK documentation (pkg.go.dev, readthedocs, etc.)
- Documentation for instrumentation libraries and plugins
- Technical specifications.

A good general rule is that we expect the audience for this site to be mostly people coming in "through the front door" - developers who are evaluating OpenTelemetry. As the cadence of releases and changes slow, it might make sense to move more documentation from the repos into the website, but we can evaluate that on a rolling basis. Again, the goal isn't necessarily to make this the _only_ source of truth, but to be more of a "first stop" that can get people started and point them towards more detailed information where necessary, and as a place to teach users and implementers about best practices for deploying and integrating OpenTelemetry into their systems and libraries.

**Closed by austinlparker** 2020-11-09 17:15 UTC
