### ISSUE TITLE
docs navigation on hover bug

### ISSUE THREAD

**Issue by Arhell** [open-telemetry/opentelemetry.io#1666] opened 2022-08-25 10:09 UTC
**What happened?**

https://opentelemetry.io/docs/
![Screenshot_1](https://user-images.githubusercontent.com/26163841/186637553-09dd1f67-6510-414b-bc12-a315184a797b.png)

**What did you expect would happen?**

or should it turn completely or not

**Comment by chalin** [comment] 2022-08-25 10:37
No, that works as intended. The UX offers feedback on the hover, which is independent (and distinct from) of the "open" or "closed" state of a nav non-leaf section.

I'm going to mark this as won't-fix and close it for now. If you feel strongly about this, that it's a misdesigned UX feature, then please open an issue over the Docsy repo: https://github.com/google/docsy.

**Closed by chalin** 2022-08-25 10:37 UTC
Labels: wontfix, design/style
