### ISSUE TITLE
Registry search breaks markdownify

### ISSUE THREAD

**Issue by svrnm** [open-telemetry/opentelemetry.io#2979] opened 2023-07-06 13:46 UTC
**What happened?** 

Go to https://opentelemetry.io/ecosystem/registry/, verify that descriptions are successfully "markdownified", e.g. use the browser search option (!) to look for  github.com/jinzhu/gorm

If I now use the search engine of the website (e.g. putting in gorm), the results are not "markdownified" any more:

https://opentelemetry.io/ecosystem/registry/?s=gorm&component=&language=

**What did you expect would happen?** 

Search should not break the formatting of descriptions

**Comment by svrnm** [comment] 2023-07-06 13:47
@chalin FYI

**Comment by chalin** [comment] 2023-07-06 13:49
Duplicate of

- #2491

**Closed** 2023-07-06 13:52 UTC
Labels: bug
