### ISSUE TITLE
[go] Getting Started docs broken

### ISSUE THREAD

**Issue by irl-segfault** [open-telemetry/opentelemetry.io#653] opened 2021-07-30 23:51 UTC
https://opentelemetry.io/docs/go/getting-started/

states you should run

```
go get go.opentelemetry.io/otel@v1.0.0-RC1 go.opentelemetry.io/otel/sdk@v1.0.0-RC1 go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0-RC1 go.opentelemetry.io/otel/trace@v1.0.0-RC1
```

This produces the error 

```console
$ go get go.opentelemetry.io/otel@v1.0.0-RC1 go.opentelemetry.io/otel/sdk@v1.0.0-RC1 go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0-RC1 go.opentelemetry.io/otel/trace@v1.0.0-RC1

go get: module go.opentelemetry.io/otel@v1.0.0-RC1 found, but does not contain package go.opentelemetry.io/otel/sdk
go get: module go.opentelemetry.io/otel@v1.0.0-RC1 found, but does not contain package go.opentelemetry.io/otel/exporters/stdout/stdouttrace
```

**Comment by chalin** [comment] 2021-08-12 12:32
/cc @tedsuo @shelbyspees @austinlparker

@MrAlias @Aneurysm9: ping. Btw, what is the process for OTel Go docs: should issues like these be moved to https://github.com/open-telemetry/opentelemetry-go/ given that the canonical sources for the doc pages are in the `opentelemetry-go` repo?

**Comment by MrAlias** [comment] 2021-08-12 17:45
I'm not able to reproduce this error.

```sh
$ uname -srvo
Linux 5.13.7-arch1-1 #1 SMP PREEMPT Sat, 31 Jul 2021 13:18:52 +0000 GNU/Linux

$ docker run --rm --env GO111MODULE=on golang:1.15 go get go.opentelemetry.io/otel@v1.0.0-RC1 go.opentelemetry.io/otel/sdk@v1.0.0-RC1 go.opentelemetry.io/otel/exporters/stdout/stdouttrace@v1.0.0-RC1 go.opentelemetry.io/otel/trace@v1.0.0-RC1
go: downloading go.opentelemetry.io/otel/trace v1.0.0-RC1
go: downloading go.opentelemetry.io/otel v1.0.0-RC1
go: downloading go.opentelemetry.io/otel/sdk v1.0.0-RC1
go: downloading go.opentelemetry.io/otel/exporters/stdout/stdouttrace v1.0.0-RC1
```

`go.opentelemetry.io/otel` does not depend on either of the stated missing packages so this seems like it might be a contextually based error.

Can you provide steps to reproduce the error and info about the environment you are running in?

**Comment by chalin** [comment] 2021-09-24 19:43
It's been over a month, so I'll close this for now. If you still have a problem, open an issue over https://github.com/open-telemetry/opentelemetry-go/edit/main/website_docs.

**Closed by chalin** 2021-09-24 19:43 UTC
Labels: go, needs-info
