### ISSUE TITLE
Aliases are not supported in a way that passes check:links command

### ISSUE THREAD

**Issue by flands** [open-telemetry/opentelemetry.io#3717] opened 2024-01-02 23:06 UTC
**What happened?** Describe the problem that occurred.

This issue is created as the result of #3714.
Have a page (page1) that is linked to by another page (page2). Change the location of page1 and attempt to add an alias to the previous location using Hugo commands.

Example:
`aliases: [page1, ../page1/]`

Run: `make check:links`

**What did you expect would happen?** Describe the expected result/output.

Test pass, but they fail because `npm run serve` is used instead of `npm run serve:netlify`

**Additional context**: anything else you can think about that would be helpful.

Aliases have been disabled in hugo.yaml and netlify is used instead.

**Comment by svrnm** [comment] 2024-01-05 08:31
> Test pass, but they fail because npm run serve is used instead of npm run serve:netlify

We had a bunch of strange issues with serve:netlify that's why we made hugo-served the default. Indeed this let's to some unexpected situations.

>  Have a page (page1) that is linked to by another page (page2). Change the location of page1 and attempt to add an alias to the previous location using Hugo commands.

If I understand you correctly the expected behaviour is that aliases are accepted by the link checker as if they were still at the previous location? I don't think this is a bug but a feature: aliases are for external parties pointing to those pages, internally we should strive to always use the right location. If a page gets moved the link checker helps to identify the pages that need to be changed.

Although I understand this adds a layer of complexity to contributors to the documentation, which is a downside we should consier making a decision here.

**Comment by chalin** [comment] 2024-01-18 11:23
Hi @flands - pretty much what @svrnm wrote: the behavior that you describe is expected, given the tooling that we use to check links. That is, **website-page links must be _canonical_** -- you cannot use aliases.

One might debate whether we'd want to change link-checking tools, but `htmltest` is **blazing fast**: it runs in less than 15 **seconds** on my machine. Given the size of our website and the number of external links, this is way faster than any other link-checking tool out there that I know of.

I actually think that it has benefits for maintainability (in the long term) for website-page links to all be canonical.

**Comment by chalin** [comment] 2024-01-18 11:24
> Test pass, but they fail because `npm run serve` is used instead of `npm run serve:netlify`

To clarify: the `htmltest` tool runs over the generated site files directly, serverless, so what you mention isn't a cause.

**Comment by chalin** [comment] 2024-01-18 11:32
I'm going to mark this as `wontfix` and close it since the behavior is expected, as I explained earlier. If you feel strongly about it, and would like to request a change of tooling, please open a separate issue.

**Closed by chalin** 2024-01-18 11:32 UTC
Labels: wontfix, infrastructure
