### ISSUE TITLE
Traces

### ISSUE THREAD

**Issue by truekonrads** [open-telemetry/opentelemetry.io#1599] opened 2022-08-06 01:45 UTC
The sample span in [this documentation page ](https://opentelemetry.io/docs/concepts/signals/traces/#spans-in-opentelemetry) does not include neither "Trace Flags" nor "Trace State". This needs either a better example span or the documentation needs adjusting.

**Comment by svrnm** [comment] 2022-08-08 09:25
@truekonrads can you provide a sample span that includes the missing details?

**Comment by svrnm** [comment] 2022-08-16 17:59
@truekonrads, I am still not 100% sure what the issue is, can you provide an example?

**Comment by cartermp** [comment] 2022-11-28 00:28
Closing this out since those are a part of `Span Context`, which is documented here: https://opentelemetry.io/docs/concepts/signals/traces/#span-context

**Closed by cartermp** 2022-11-28 00:28 UTC
Labels: docs, e0-minutes, needs-info
