### ISSUE TITLE
Calendar View for End User Events

### ISSUE THREAD

**Issue by rafey1104** [open-telemetry/opentelemetry.io#4098] opened 2024-03-05 16:35 UTC
I am going to implement this feature request (https://github.com/open-telemetry/community/issues/1962)

**Comment by rafey1104** [comment] 2024-03-05 16:45
Hi @austinlparker @chalin @cartermp @svrnm 
Please any one of you assign me this issue

**Comment by cartermp** [comment] 2024-03-05 17:37
@rafey1104 we don't assign issues typically. Feel free to just proceed if you're interested in contributing.

**Comment by svrnm** [comment] 2024-03-07 07:10
thanks @rafey1104, can you share some details on how you plan to implement this? Feel free to drop us a draft PR early so we can take a look!

cc @open-telemetry/end-user-wg

**Comment by rafey1104** [comment] 2024-03-08 06:01
@svrnm I will be get back to you shortly

**Comment by rafey1104** [comment] 2024-03-08 09:31
> @rafey1104 we don't assign issues typically. Feel free to just proceed if you're interested in contributing.
@cartermp Can you please tell me which specific node LTS version should i be using to set up the local environment? 
/

**Comment by rafey1104** [comment] 2024-03-08 09:41
> thanks @rafey1104, can you share some details on how you plan to implement this? Feel free to drop us a draft PR early so we can take a look!
> 
> cc @open-telemetry/end-user-wg

Am I free to use any tech stack to develop the solution? I am thinking of using React.js for the front end, Next.js for Frontend & Backend,  Typescript for greater type safety, and Tailwind.css for Styling.

**Comment by rafey1104** [comment] 2024-03-08 09:46
> @rafey1104 we don't assign issues typically. Feel free to just proceed if you're interested in contributing.

which specific node LTS version should I be using to set up the local development environment? I don't want to waste my time trying to figure it out myself 
![Screenshot (393)](https://github.com/open-telemetry/opentelemetry.io/assets/60809612/a67cf4c5-b8d3-48cc-91e2-202a57e527ca)

**Comment by svrnm** [comment] 2024-03-08 09:51
> > thanks @rafey1104, can you share some details on how you plan to implement this? Feel free to drop us a draft PR early so we can take a look!
> > cc @open-telemetry/end-user-wg
> 
> Am I free to use any tech stack to develop the solution? I am thinking of using React.js for the front end, Next.js for Frontend & Backend, Typescript for greater type safety, and Tailwind.css for Styling.

That's unfortunately not going to work, there are 2 options how this can be resolved:
(a) You can do research if we can get a web view from google calendar like [this one](https://calendar.google.com/calendar/u/0/embed?src=c_2bf73e3b6b530da4babd444e72b76a6ad893a5c3f43cf40467abc7a9a897f977@group.calendar.google.com) only showing the EUWG events. You will not have the privileges for that so you may need to create a dummy calendar and experiment with that
(b) You find a way to include the calendar view in the existing homepage (for example https://opentelemetry.io/community/end-user/calendar). This means it has to work with hugo, so either you find some javascript magic that pulls in the right events from the client side. Or (which is my preferred solution), you find a way that we can get those events pulled into the repository on a regular basis (e.g. with a github workflow into the data folder) and publish from there. Or any other _creative_ solution that works with what we have today.

for your other question, try `nvm install --lts`, I think that needs to be fixed.

**Comment by rafey1104** [comment] 2024-03-10 02:46
Okay, thanks for the info

**Comment by rafey1104** [comment] 2024-03-10 04:12
@svrnm   Can you please help me resolve this error? I am unable to setup the development environment. I have already tested the Calendar integration in my local environment, just waiting for the development environment to be up so that i can integrate the changes 
![Screenshot from 2024-03-10 09-37-27](https://github.com/open-telemetry/opentelemetry.io/assets/60809612/94c933b7-091b-40c6-af73-3f18b1b6bb9d)

**Comment by svrnm** [comment] 2024-03-11 08:45
@rafey1104 can you share the log file?

**Comment by rafey1104** [comment] 2024-03-12 07:25
[logs.pdf](https://github.com/open-telemetry/opentelemetry.io/files/14568707/logs.pdf)
@svrnm

**Comment by rafey1104** [comment] 2024-03-12 13:43
https://gist.github.com/rafey1104/b5295d6c1a1454b4bc878d855144770c

**Comment by svrnm** [comment] 2024-03-12 13:54
@rafey1104 I can not really figure out from that log what the problem is, at the bottom it starts to complain about some optional dependencies not being able to be installed.

Can you remove the `node_modules` folder in your local install and give it another try? And, if that does not work make a fresh clone of this repo and try it that way? Something seems off to me

**Comment by rafey1104** [comment] 2024-03-13 01:34
@svrnm Thanks for the help. As I was getting some unexpected errors in the local environment I used GitHub codespaces and now the site is up and running. I will shortly create a pull request

**Comment by danielgblanco** [comment] 2024-05-30 13:30
We currently have https://github.com/open-telemetry/sig-end-user/issues/8 in progress, which will allow us to organise events as part of a CNCF Community Group. See an example for [Keptn](https://community.cncf.io/keptn-community/).

Could this issue be solved by using pointing users in our website to the CNCF Community Group page (when it's created)?

**Comment by svrnm** [comment] 2024-06-03 10:26
Yes 🙌 , that sounds like a solution. If we want "more" I guess there is a way to pull that data from the community group page?

**Comment by danielgblanco** [comment] 2024-06-17 10:31
I will find out more about that when we get the community group, but as a start we will link the community group directly on our website, with all their events.

Closing this issue for now.

**Closed by danielgblanco** 2024-06-17 10:31 UTC
Labels: sig:enduser
